version: '3.2'

services:
    db:
        image: mysql:8.0.19
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql_database
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: yii2advanced
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.8.4
        container_name: phpmyadmin_web
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            UPLOAD_LIMIT: 128M
        ports:
            - 8080:80
        depends_on:
            - db

    init:
        build: frontend
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ./:/app
        env_file:
            - ./server.env
        depends_on:
            - db
        command: >
            bash -c "composer install
            && php init --env=$${ENV_NAME} --overwrite=All
            && php /app/yii migrate --interactive=0"

    frontend:
        build: frontend
        ports:
            - 20080:80
        volumes:
            # Re-use local composer cache via host-volume
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            # Mount source-code for development
            - ./:/app
        depends_on:
            - db
            - init
        env_file:
            - ./server.env

    backend:
        build: backend
        ports:
            - 21080:80
        volumes:
            # Re-use local composer cache via host-volume
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            # Mount source-code for development
            - ./:/app
        depends_on:
            - db
            - init
        env_file:
            - ./server.env

    cdn:
        image: nginx:alpine
        restart: always
        ports:
            - 21110:80
        volumes:
            - "./cdn:/usr/share/nginx/html"
            - "./.docker-data/nginx/conf.d:/etc/nginx/conf.d"
