version: '3.2'

services:
    db:
        image: mysql:8.0.19
        command: --default-authentication-plugin=mysql_native_password
        container_name: vm_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: vm_db

    redis:
        image: redis:5.0
        container_name: vm_redis

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:4.8.4
        container_name: vm_phpmyadmin
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            UPLOAD_LIMIT: 128M
        ports:
            - 8080:80
        depends_on:
            - db

    init:
        build: frontend
        container_name: vm_init
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ./:/app
        env_file:
            - ./docker.env
        depends_on:
            - db
        command: >
            sh -c "composer install
            && php init --env=$${ENV_NAME} --overwrite=All
            && php /app/yii migrate --interactive=0
            && php /app/yii migrate --migrationPath=@app/migrations/fake --interactive=0
            && php yii user/create-admin "admin" "admin""

    frontend:
        build: frontend
        container_name: vm_frontend
        ports:
            - 20080:80
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ./:/app
        depends_on:
            - db
        env_file:
            - ./docker.env

    backend:
        build: backend
        container_name: vm_backend
        ports:
            - 21080:80
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ./:/app
        depends_on:
            - db
        env_file:
            - ./docker.env

    api:
        build: api
        container_name: vm_api
        ports:
            - 21088:80
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ./:/app
        depends_on:
            - db
        env_file:
            - ./docker.env

    cdn:
        image: nginx:alpine
        container_name: vm_cdn
        ports:
            - 21110:80
        volumes:
            - "./cdn:/usr/share/nginx/html"
            - "./.docker-data/nginx/conf.d:/etc/nginx/conf.d"
